version: "2.2"
services:
  db:
    container_name: fastJava-mysql
    image: mysql:5.7.22
    ports:
    - 3309:3306
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_DATABASE: "fastJava"
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    container_name: my-redis
    image: redis
    ports:
    - 6379:6379
    restart: always